#! /bin/sh
#
# Author:	Christian Paradis
#

# Exit immediately if a pipeline, which may consist of a single simple command, a list, or a
# compound command returns a non-zero status.
set -e

case "$1" in
  start)
	echo "Starting aesdsocket server daemon..."
	start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -d
	echo $?
    ;;
  stop)
	echo "Stopping aesdsocket server daemon..."
	start-stop-daemon -K -n aesdsocket
	echo $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/S99aesdsocket {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
